device: cuda:5
note: "k60_rad256_flatformerTrans"
seed: 42
log_tensorboard: true
num_threads: 5


model_name: trans_flatformer
model_kwargs:
  num_slices_per_axis: 30
  group_size: 200
  pe_type: learned
  B: 1000
  num_heads: 8
  h_dim: 20
  n_layers: 2
  num_w_per_dist: 10


loss_name: infonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 2000
batch_size: 1
optimizer_kwargs:
  lr: 1.0e-3


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 500


data_dir: ../data/
dataset_name: tracking-6k
main_metric: accuracy@0.9
mode: max
